// js/tests/test_reports.spec.js
// Tests for the printable summary report (js/reports/index.js).

const test = require("node:test");
const assert = require("node:assert/strict");

const dm = require("../data_model.js");
const engine = require("../tax_engine.js");
const reports = require("../reports/index.js");

// ============================================================
// buildReport
// ============================================================

test("buildReport: returns a non-empty string", () => {
  const wb = dm.emptyWorkbook("2025-26");
  wb.personal.name = "Test User";
  wb.salary.employers = [{ employer_name: "A", tan: "", gross_salary: 1000000, allowances_exempt_10: 0, professional_tax: 0 }];
  const tr = engine.computeBothRegimes(wb);
  const report = reports.buildReport(wb, tr);
  assert.ok(typeof report === "string");
  assert.ok(report.length > 100);
});

test("buildReport: contains key sections", () => {
  const wb = dm.emptyWorkbook("2025-26");
  wb.personal.name = "Test User";
  wb.personal.pan = "ABCDE1234F";
  wb.salary.employers = [{ employer_name: "A", tan: "", gross_salary: 1000000, allowances_exempt_10: 0, professional_tax: 0 }];
  const tr = engine.computeBothRegimes(wb);
  const report = reports.buildReport(wb, tr);
  // Headline
  assert.match(report, /ITRready/);
  assert.match(report, /2025-26/);
  // Personal
  assert.match(report, /Test User/);
  assert.match(report, /ABCDE1234F/);
  // Income
  assert.match(report, /Salary/);
  assert.match(report, /GROSS TOTAL INCOME/);
  // Deductions
  assert.match(report, /DEDUCTIONS/);
  // Tax computation
  assert.match(report, /TAX COMPUTATION/);
  assert.match(report, /Slab tax/);
  assert.match(report, /TOTAL TAX LIABILITY/);
  // Regime comparison
  assert.match(report, /REGIME COMPARISON/);
  assert.match(report, /RECOMMENDATION/);
  // Footer
  assert.match(report, /Generated by ITRready/);
});

test("buildReport: shows schedule CG section when capital gains present", () => {
  const wb = dm.emptyWorkbook("2025-26");
  wb.capital_gains.stcg_111a = 200000;
  const tr = engine.computeBothRegimes(wb);
  const report = reports.buildReport(wb, tr);
  assert.match(report, /Schedule CG/);
  assert.match(report, /STCG 111A @ 15%/);
});

test("buildReport: hides schedule CG section when no capital gains", () => {
  const wb = dm.emptyWorkbook("2025-26");
  wb.salary.employers = [{ employer_name: "A", tan: "", gross_salary: 1000000, allowances_exempt_10: 0, professional_tax: 0 }];
  const tr = engine.computeBothRegimes(wb);
  const report = reports.buildReport(wb, tr);
  assert.doesNotMatch(report, /Schedule CG total/);
});

test("buildReport: shows 234B/234C interest when applicable", () => {
  const wb = dm.emptyWorkbook("2025-26");
  wb.salary.employers = [{ employer_name: "A", tan: "", gross_salary: 2000000, allowances_exempt_10: 0, professional_tax: 0 }];
  // No TDS → 234B/C interest non-zero
  const tr = engine.computeBothRegimes(wb);
  const report = reports.buildReport(wb, tr);
  assert.match(report, /INTEREST u\/s 234/);
});

test("buildReport: masks bank account in personal info section", () => {
  const wb = dm.emptyWorkbook("2025-26");
  wb.personal.bank_for_refund.account_number = "1234567890";
  const tr = engine.computeBothRegimes(wb);
  const report = reports.buildReport(wb, tr);
  assert.match(report, /\*\*\*\*\*\*7890/);
  assert.doesNotMatch(report, /1234567890/);
});

test("buildReport: reflects chosen regime from opts.recommended", () => {
  const wb = dm.emptyWorkbook("2025-26");
  wb.salary.employers = [{ employer_name: "A", tan: "", gross_salary: 1500000, allowances_exempt_10: 0, professional_tax: 0 }];
  const tr = engine.computeBothRegimes(wb);
  // Force "old" regime even if the engine recommends "new"
  const report = reports.buildReport(wb, tr, { recommended: "old" });
  // The header "TAX COMPUTATION (old regime)" should appear
  assert.match(report, /TAX COMPUTATION \(Old regime/);
});

test("buildReport: missing workbook throws", () => {
  assert.throws(() => reports.buildReport(null, {}));
});

test("buildReport: missing taxResult throws", () => {
  const wb = dm.emptyWorkbook("2025-26");
  assert.throws(() => reports.buildReport(wb, null));
  assert.throws(() => reports.buildReport(wb, {}));
});

// ============================================================
// buildOneLiner
// ============================================================

test("buildOneLiner: returns a one-line summary", () => {
  const wb = dm.emptyWorkbook("2025-26");
  wb.salary.employers = [{ employer_name: "A", tan: "", gross_salary: 1500000, allowances_exempt_10: 0, professional_tax: 0 }];
  const tr = engine.computeBothRegimes(wb);
  const line = reports.buildOneLiner(tr);
  assert.ok(typeof line === "string");
  assert.ok(line.length > 0);
  assert.ok(line.length < 200);
});

test("buildOneLiner: tie → mentions no difference", () => {
  const wb = dm.emptyWorkbook("2025-26");
  // Empty workbook → both regimes 0
  const tr = engine.computeBothRegimes(wb);
  if (tr.recommendation === "tie") {
    const line = reports.buildOneLiner(tr);
    assert.match(line, /No regime difference|Both regimes/);
  }
});

test("buildOneLiner: non-tie → mentions winning regime", () => {
  const wb = dm.emptyWorkbook("2025-26");
  wb.salary.employers = [{ employer_name: "A", tan: "", gross_salary: 1500000, allowances_exempt_10: 0, professional_tax: 0 }];
  const tr = engine.computeBothRegimes(wb);
  if (tr.recommendation !== "tie") {
    const line = reports.buildOneLiner(tr);
    assert.match(line, /(Old|New) regime wins/);
  }
});

// ============================================================
// Internal helpers (exposed for tests)
// ============================================================

test("fmtRs helper: positive", () => {
  assert.equal(reports._internal.fmtRs(100000), "₹1,00,000");
  assert.equal(reports._internal.fmtRs(0), "₹0");
});

test("fmtRs helper: negative", () => {
  assert.equal(reports._internal.fmtRs(-50000), "-₹50,000");
});

test("fmtRs helper: null / undefined / NaN → ₹0", () => {
  assert.equal(reports._internal.fmtRs(null), "₹0");
  assert.equal(reports._internal.fmtRs(undefined), "₹0");
  assert.equal(reports._internal.fmtRs(NaN), "₹0");
});

test("pct helper", () => {
  assert.equal(reports._internal.pct(0.10), "10.00%");
  assert.equal(reports._internal.pct(0.0), "0.00%");
  assert.equal(reports._internal.pct(NaN), "0%");
});

test("buildHeader: includes AY and FY", () => {
  const wb = dm.emptyWorkbook("2025-26");
  const header = reports._internal.buildHeader(wb);
  assert.match(header, /2025-26/);
  assert.match(header, /2024-25/);
});

test("buildPersonalInfo: includes name and PAN when set", () => {
  const wb = dm.emptyWorkbook("2025-26");
  wb.personal.name = "John Doe";
  wb.personal.pan = "ABCDE1234F";
  const sec = reports._internal.buildPersonalInfo(wb);
  assert.match(sec, /John Doe/);
  assert.match(sec, /ABCDE1234F/);
});

test("buildRegimeComparison: contains both regimes", () => {
  const wb = dm.emptyWorkbook("2025-26");
  wb.salary.employers = [{ employer_name: "A", tan: "", gross_salary: 1500000, allowances_exempt_10: 0, professional_tax: 0 }];
  const tr = engine.computeBothRegimes(wb);
  const sec = reports._internal.buildRegimeComparison(tr);
  assert.match(sec, /OLD REGIME/);
  assert.match(sec, /NEW REGIME/);
});

test("buildFooter: contains generator info", () => {
  const sec = reports._internal.buildFooter();
  assert.match(sec, /ITRready/);
  assert.match(sec, /Generated at/);
});
